package net.slc.dv.resources;

import java.util.HashMap;
import java.util.Map;
import net.slc.dv.enums.Language;

public enum Text {
    ANSWER_SAVED(
            "Answer Saved",
            "Jawaban Tersimpan",
            "回答が保存されました",
            "Respuesta guardada",
            "Antwoord opgeslagen",
            "答案已保存",
            "답변 저장됨",
            "उत्तर सहेजा गया",
            "تم حفظ الإجابة",
            "Đã lưu câu trả lời"),
    SAVE("Save", "Simpan", "保存", "Guardar", "Opslaan", "保存", "저장", "सहेजें", "حفظ", "Lưu"),
    TRUE("True", "Benar", "真", "Verdadero", "Waar", "真", "참", "सच", "صحيح", "Đúng"),
    TASK("Task", "Tugas", "タスク", "Tarea", "Taak", "任务", "작업", "कार्य", "مهمة", "Nhiệm vụ"),
    TEST("Test", "Ujian", "テスト", "Prueba", "Test", "测试", "시험", "परीक्षण", "اختبار", "Kiểm tra"),
    HOME("Home", "Beranda", "ホーム", "Inicio", "Thuis", "家", "집", "घर", "الصفحة الرئيسية", "Trang chủ"),
    CALENDAR("Calendar", "Kalender", "カレンダー", "Calendario", "Kalender", "日历", "달력", "कैलेंडर", "التقويم", "Lịch"),
    LOGOUT(
            "Logout",
            "Keluar",
            "ログアウト",
            "Cerrar sesión",
            "Uitloggen",
            "登出",
            "로그 아웃",
            "लॉग आउट",
            "تسجيل خروج",
            "Đăng xuất"),
    FILE_TOO_BIG(
            "File size exceeded 100kb",
            "Ukuran file melebihi 100kb",
            "ファイルサイズが100kbを超えています",
            "El tamaño del archivo supera los 100 kb",
            "Bestandsgrootte overschrijdt 100 kb",
            "文件大小超过100kb",
            "파일 크기가 100kb를 초과합니다",
            "फ़ाइल का आकार 100kb से अधिक है",
            "حجم الملف تجاوز 100 كيلوبايت",
            "Kích thước tệp vượt quá 100kb"),
    EMAIL_ALREADY_EXISTS(
            "Email already exists",
            "Email sudah dipakai",
            "メールアドレスは既に存在します",
            "El correo electrónico ya existe",
            "E-mail bestaat al",
            "电子邮件已存在",
            "이메일이 이미 있습니다",
            "ईमेल पहले से मौजूद है",
            "البريد الإلكتروني موجود بالفعل",
            "Email đã tồn tại"),
    INVALID_DATE_FORMAT(
            "Invalid date format",
            "Format tanggal tidak valid",
            "無効な日付形式",
            "Formato de fecha no válido",
            "Ongeldige datumnotatie",
            "无效的日期格式",
            "잘못된 날짜 형식",
            "अमान्य तारीख प्रारूप",
            "تنسيق التاريخ غير صالح",
            "Định dạng ngày không hợp lệ"),
    UPDATE_PROFILE(
            "Update Profile",
            "Perbarui Profil",
            "プロフィールを更新",
            "Actualizar perfil",
            "Profiel bijwerken",
            "更新个人资料",
            "프로필 업데이트",
            "प्रोफ़ाइल अपडेट करें",
            "تحديث الملف الشخصي",
            "Cập nhật hồ sơ"),
    CANCEL("Cancel", "Batal", "キャンセル", "Cancelar", "Annuleren", "取消", "취소", "रद्द करना", "إلغاء", "Hủy bỏ"),
    OLD_PASSWORD(
            "Old Password",
            "Kata Sandi Lama",
            "古いパスワード",
            "Contraseña anterior",
            "Oud wachtwoord",
            "旧密码",
            "이전 비밀번호",
            "पुराना पासवर्ड",
            "كلمة المرور القديمة",
            "Mật khẩu cũ"),
    NEW_PASSWORD(
            "New Password",
            "Kata Sandi Baru",
            "新しいパスワード",
            "Nueva contraseña",
            "Nieuw wachtwoord",
            "新密码",
            "새 비밀번호",
            "नया पासवर्ड",
            "كلمة مرور جديدة",
            "Mật khẩu mới"),
    UPDATE_PASSWORD(
            "Update Password",
            "Perbarui Kata Sandi",
            "パスワードを更新",
            "Actualizar contraseña",
            "Wachtwoord bijwerken",
            "更新密码",
            "비밀번호 업데이트",
            "पासवर्ड अपडेट करें",
            "تحديث كلمة المرور",
            "Cập nhật mật khẩu"),
    SELECT_PROFILE_PICTURE(
            "Select Profile Picture",
            "Pilih Foto Profil",
            "プロフィール画像を選択",
            "Seleccionar foto de perfil",
            "Profielfoto selecteren",
            "选择个人资料图片",
            "프로필 사진 선택",
            "प्रोफ़ाइल चित्र चुनें",
            "حدد صورة الملف الشخصي",
            "Chọn hình đại diện"),
    IMAGE_FILES(
            "Image Files",
            "File Gambar",
            "画像ファイル",
            "Archivos de imagen",
            "Afbeeldingsbestanden",
            "图像文件",
            "이미지 파일",
            "छवि फाइलें",
            "ملفات الصور",
            "Tập tin hình ảnh"),
    FILE("File", "File", "ファイル", "Archivo", "Bestand", "文件", "파일", "फ़ाइल", "ملف", "Tập tin"),
    SUCCESS("Success", "Sukses", "成功", "Éxito", "Succes", "成功", "성공", "सफलता", "نجاح", "Thành công"),
    UNEXPECTED_ERROR(
            "Unexpected Error",
            "Kesalahan Tidak Terduga",
            "予期しないエラー",
            "Error inesperado",
            "Onverwachte fout",
            "意外的错误",
            "예기치 않은 오류",
            "अप्रत्याशित त्रुटि",
            "خطأ غير متوقع",
            "Lỗi bất ngờ"),
    EDIT_PROFILE(
            "Edit Profile",
            "Edit Profil",
            "プロフィールを編集",
            "Editar perfil",
            "Profiel bewerken",
            "编辑个人资料",
            "프로필 편집",
            "प्रोफ़ाइल संपादित करें",
            "تعديل الملف الشخصي",
            "Chỉnh sửa hồ sơ"),
    CHANGE_PASSWORD(
            "Change Password",
            "Ubah Kata Sandi",
            "パスワードを変更",
            "Cambiar contraseña",
            "Wachtwoord wijzigen",
            "更改密码",
            "비밀번호 변경",
            "पासवर्ड बदलें",
            "تغيير كلمة المرور",
            "Thay đổi mật khẩu"),
    PENDING_TASK(
            "Pending Task",
            "Tugas yang Menunggu",
            "保留中のタスク",
            "Tarea pendiente",
            "In afwachting van taak",
            "待处理的任务",
            "보류 중인 작업",
            "विचाराधीन कार्य",
            "مهمة معلقة",
            "Nhiệm vụ đang chờ"),
    FINISHED_TASK(
            "Finished Task",
            "Tugas Selesai",
            "終了したタスク",
            "Tarea terminada",
            "Afgewerkte taak",
            "完成的任务",
            "완료된 작업",
            "समाप्त कार्य",
            "مهمة منتهية",
            "Nhiệm vụ đã hoàn thành"),
    LETS_CHILL(
            "Chill Yeah??",
            "Santai dulu gak sih?",
            "リラックスしましょう！",
            "Relajémonos",
            "Laten we ontspannen",
            "让我们放松",
            "쉬자!",
            "चलो ठहरो!",
            "دعونا نسترخي!",
            "Hãy thư giãn!"),
    JOIN_CLASS(
            "Join Class",
            "Bergabung ke Kelas",
            "クラスに参加",
            "Unirse a la clase",
            "Sluit je aan bij de klas",
            "加入班级",
            "클래스에 참여",
            "कक्षा में शामिल हों",
            "انضم إلى الفصل",
            "Tham gia lớp"),
    CREATE_CLASS(
            "Create Class",
            "Buat Kelas",
            "クラスを作成",
            "Crear clase",
            "Maak klas",
            "创建班级",
            "클래스 만들기",
            "कक्षा बनाएं",
            "إنشاء فصل دراسي",
            "Tạo lớp"),
    EMPTY_CLASSROOM_DEAR("Dear", "Hai", "親愛なる", "Querido", "Beste", "亲爱的", "친애하는", "प्रिय", "عزيزي", "Thân mến"),

    // String english, String indonesian, String japanese, String spanish, String dutch, String chinese, String korean,
    // String indian, String arabic, String vietnamese) {
    EMPTY_CLASSROOM_DESCRIPTION_ONE(
            "Welcome to an exciting journey of learning and discovery with DigiVerse! I am thrilled to have each and every one of you in our class. This promises to be a rewarding and enriching experience, filled with opportunities for growth, collaboration, and success.",
            "Selamat datang di perjalanan belajar dan penemuan yang menarik dengan DigiVerse! Saya sangat senang memiliki setiap orang dari kalian di kelas kami. Ini menjanjikan pengalaman yang memuaskan dan memperkaya, penuh dengan peluang untuk pertumbuhan, kolaborasi, dan kesuksesan.",
            "DigiVerseと一緒に学びと発見のエキサイティングな旅にようこそ！私は私たちのクラスにあなた方一人一人を迎えることをとても嬉しく思っています。これは、成長、協力、成功の機会に満ちた、報酬の高い、豊かな経験になることを約束しています。",
            "¡Bienvenido a un emocionante viaje de aprendizaje y descubrimiento con DigiVerse! Estoy encantado de tener a cada uno de ustedes en nuestra clase. Esto promete ser una experiencia gratificante y enriquecedora, llena de oportunidades de crecimiento, colaboración y éxito.",
            "Welkom bij een spannende reis van leren en ontdekken met DigiVerse! Ik ben verheugd om ieder van jullie in onze klas te hebben. Dit belooft een lonende en verrijkende ervaring te worden, vol met kansen voor groei, samenwerking en succes.",
            "DigiVerse欢迎您加入令人兴奋的学习和发现之旅！我很高兴在我们的课堂上有你们每一个人。这将是一次有益和丰富的经历，充满了成长，合作和成功的机会。",
            "DigiVerse와 함께하는 흥미 진진한 학습 및 발견 여행에 오신 것을 환영합니다! 저는 우리 반에 여러분을 모두 환영합니다. 이것은 성장, 협력, 성공의 기회로 가득 찬 보상이 많고 풍부한 경험이 될 것이라고 약속합니다.",
            "DigiVerse के साथ एक रोमांचक यात्रा में सीखने और खोज करने के लिए आपका स्वागत है! मुझे हमारी कक्षा में आप सभी का स्वागत है। यह एक बहुत बड़ा और आर्थिक रूप से संवृद्धि और आर्थिक रूप से संवृद्धि का वादा करता है, जिसमें विकास, सहयोग और सफलता के अवसरों से भरपूर एक बहुत बड़ा और आर्थिक रूप से संवृद्धि और आर्थिक रूप से संवृद्धि का वादा करता है।",
            "¡Bienvenido a un emocionante viaje de aprendizaje y descubrimiento con DigiVerse! Estoy encantado de tener a cada uno de ustedes en nuestra clase. Esto promete ser una experiencia gratificante y enriquecedora, llena de oportunidades de crecimiento, colaboración y éxito.",
            "Chào mừng bạn đến với một hành trình học tập và khám phá thú vị với DigiVerse! Tôi rất vui mừng khi có mỗi người trong số bạn trong lớp học của chúng tôi. Điều này hứa hẹn sẽ là một trải nghiệm đáng giá và bổ ích, đầy cơ hội để phát triển, hợp tác và thành công."),

    EMPTY_CLASSROOM_DESCRIPTION_TWO(
            "In this application, we value curiosity, creativity, and the pursuit of knowledge. Together, we will explore new concepts, engage in meaningful discussions, and support one another on our academic endeavors.",
            "Dalam aplikasi ini, kami menghargai rasa ingin tahu, kreativitas, dan hasrat untuk pengetahuan. Bersama-sama, kita akan menjelajahi konsep-konsep baru, tergabung dalam diskusi yang berarti, dan mendukung satu sama lain dalam upaya akademik kita.",
            "このアプリケーションでは、好奇心、創造性、そして知識の追求を重視しています。一緒に新しいコンセプトを探求し、意味のある議論に参加し、お互いを学術的な努力で支援します。",
            "En esta aplicación, valoramos la curiosidad, la creatividad y la búsqueda del conocimiento. Juntos, exploraremos nuevos conceptos, participaremos en discusiones significativas y nos apoyaremos mutuamente en nuestros esfuerzos académicos.",
            "In deze applicatie waarderen we nieuwsgierigheid, creativiteit en het streven naar kennis. Samen zullen we nieuwe concepten verkennen, deelnemen aan betekenisvolle discussies en elkaar ondersteunen in onze academische inspanningen.",
            "在这个应用程序中，我们重视好奇心，创造力和对知识的追求。我们将一起探索新的概念，参与有意义的讨论，并在我们的学术努力中相互支持。",
            "이 애플리케이션에서는 호기심, 창의성 및 지식의 추구를 중요시합니다. 함께 새로운 개념을 탐색하고 의미있는 토론에 참여하며 서로의 학업 노력을 지원합니다.",
            "इस एप्लिकेशन में, हम जिज्ञासा, रचनात्मकता और ज्ञान की प्रतिक्षा को महत्व देते हैं। साथ में, हम नए अवधारणाओं का अन्वेषण करेंगे, मानवीय चर्चाओं में शामिल होंगे, और अपने शैक्षिक प्रयासों में एक दूसरे का समर्थन करेंगे।",
            "En esta aplicación, valoramos la curiosidad, la creatividad y la búsqueda del conocimiento. Juntos, exploraremos nuevos conceptos, participaremos en discusiones significativas y nos apoyaremos mutuamente en nuestros esfuerzos académicos.",
            "Trong ứng dụng này, chúng tôi coi trọng tính tò mò, tính sáng tạo và sự khao khát tìm hiểu. Cùng nhau, chúng ta sẽ khám phá các khái niệm mới, tham gia vào các cuộc thảo luận có ý nghĩa và hỗ trợ lẫn nhau trong những nỗ lực học tập của chúng ta."),
    EMPTY_CLASSROOM_DESCRIPTION_THREE(
            "We look forward to getting to know each of you and learning with you this year.",
            "Kami berharap untuk mengenal masing-masing dari kalian dan belajar bersama-sama tahun ini.",
            "今年は皆さんとお会いできるのを楽しみにしています。",
            "Esperamos conocerlos a cada uno de ustedes y aprender con ustedes este año.",
            "We kijken ernaar uit om jullie dit jaar te leren kennen en met jullie te leren.",
            "我们期待着认识你们每一个人，并与你们一起学习。",
            "우리는 올해 여러분을 알고 여러분과 함께 배우기를 기대합니다.",
            "हम आपको इस साल जानने और साथ में सीखने की उम्मीद करते हैं।",
            "نتطلع إلى التعرف على كل واحد منكم والتعلم معكم هذا العام.",
            "Chúng tôi mong muốn được biết về mỗi người trong số bạn và học cùng bạn trong năm nay."),
    EMPTY_CLASSROOM_DESCRIPTION_FOUR(
            "Let's make this a fantastic academic journey together!",
            "Mari kita jadikan ini perjalanan akademik yang fantastis bersama!",
            "一緒に素晴らしい学術的な旅をしましょう！",
            "¡Hagamos de este un viaje académico fantástico juntos!",
            "Laten we er samen een fantastische academische reis van maken!",
            "让我们一起度过这段美妙的学术旅程！",
            "함께 환상적인 학술 여행을 만들어 봅시다!",
            "चलो इसे एक शानदार शैक्षणिक यात्रा बनाएं!",
            "لنجعل من هذه رحلة أكاديمية رائعة معًا!",
            "Hãy cùng nhau tạo nên một hành trình học tập tuyệt vời này!"),
    EMPTY_CLASSROOM_SINCERELY(
            "Sincerely,",
            "Dengan Hormat,",
            "敬具",
            "Sinceramente,",
            "Oprecht,",
            "真诚地",
            "존중하는",
            "आभारी",
            "بإخلاص,",
            "Trân trọng,"),
    TO_JOIN_CLASS(
            "To join using group class code:",
            "Untuk bergabung dengan kode kelas grup:",
            "グループクラスコードを使用して参加するには：",
            "Para unirse usando el código de clase grupal:",
            "Om lid te worden met behulp van de groepscode van de klas:",
            "要使用组课程代码加入：",
            "그룹 클래스 코드를 사용하여 가입하려면:",
            "समूह कक्षा कोड का उपयोग करके शामिल होने के लिए:",
            "للانضمام باستخدام رمز فئة المجموعة:",
            "Để tham gia bằng cách sử dụng mã lớp nhóm:"),
    JOIN_CLASS_REQUIREMENT_ONE(
            "• Use an authorized account",
            "• Gunakan akun yang diotorisasi",
            "• 承認されたアカウントを使用する",
            "• Usa una cuenta autorizada",
            "• Gebruik een geautoriseerd account",
            "• 使用授权帐户",
            "• 승인 된 계정을 사용하십시오",
            "• एक अधिकृत खाता उपयोग करें",
            "• استخدم حساب معتمد",
            "• Sử dụng tài khoản được ủy quyền"),
    JOIN_CLASS_REQUIREMENT_TWO(
            "• Use a maximum of 10 letters of group code.",
            "• Gunakan maksimal 10 huruf dari kode grup.",
            "• グループコードの最大文字数は10文字です。",
            "• Use un máximo de 10 letras del código de grupo.",
            "• Gebruik maximaal 10 letters van de groepscode.",
            "• 使用组代码的最大字母数为10个。",
            "• 그룹 코드의 최대 문자 수는 10 자입니다.",
            "• समूह कोड के 10 अक्षरों का उपयोग करें।",
            "• استخدم حد أقصى 10 أحرف من رمز المجموعة.",
            "• Sử dụng tối đa 10 chữ cái của mã nhóm."),
    CLASS_JOINED(
            "Class Joined",
            "Bergabung dengan Kelas",
            "クラスに参加しました",
            "Clase unida",
            "Klas toegevoegd",
            "班级加入",
            "클래스 가입",
            "कक्षा जुड़ी",
            "الصف ملحق",
            "Lớp học đã tham gia"),
    LOGGED_AS(
            "Logged As",
            "Masuk Sebagai",
            "としてログイン",
            "Registrado como",
            "Aangemeld als",
            "登录为",
            "로 로그인",
            "के रूप में लॉग इन",
            "تم تسجيل الدخول باسم",
            "Đã đăng nhập như"),
    CHANGE_ACCOUNT(
            "Change Account",
            "Ganti Akun",
            "アカウントを変更",
            "Cambiar cuenta",
            "Account wijzigen",
            "更改帐户",
            "계정 변경",
            "खाता बदलें",
            "تغيير الحساب",
            "Thay đổi tài khoản"),
    GROUP_CODE(
            "Group Code",
            "Kode Kelompok",
            "グループコード",
            "Código de grupo",
            "Groepscode",
            "组代码",
            "그룹 코드",
            "समूह कोड",
            "رمز المجموعة",
            "Mã nhóm"),
    ENTER_THE_GROUP_CODE(
            "Enter the group code given by your teacher",
            "Masukkan kode grup yang diberikan oleh guru Anda",
            "先生からもらったグループコードを入力してください",
            "Ingrese el código de grupo proporcionado por su profesor",
            "Voer de groepscode in die door uw leraar is gegeven",
            "输入老师给的组代码",
            "선생님이 제공 한 그룹 코드를 입력하십시오",
            "अपने शिक्षक द्वारा दिए गए समूह कोड दर्ज करें",
            "أدخل رمز المجموعة الذي يتم تقديمه من قبل معلمك",
            "Nhập mã nhóm được cung cấp bởi giáo viên của bạn"),
    JOIN("Join", "Gabung", "参加", "Unirse", "Meedoen", "加入", "가입", "शामिल हों", "انضم", "Tham gia"),
    WRITE_A_COMMENT(
            "Write a comment",
            "Tulis komentar",
            "コメントを書く",
            "Escribir un comentario",
            "Schrijf een opmerking",
            "写评论",
            "댓글 쓰기",
            "एक टिप्पणी लिखें",
            "اكتب تعليقًا",
            "Viết bình luận"),
    WHATS_ON_YOUR_MIND(
            "What's on your mind",
            "Apa yang ada di pikiranmu",
            "今何を考えていますか",
            "¿Qué tienes en mente?",
            "Wat heb je in gedachten",
            "你在想什么",
            "무슨 생각이야",
            "आपके दिमाग में क्या है",
            "ما الذي يدور في ذهنك",
            "Bạn đang nghĩ gì"),
    CLASS_CODE(
            "Class Code",
            "Kode Kelas",
            "クラスコード",
            "Código de clase",
            "Klascode",
            "班级代码",
            "클래스 코드",
            "कक्षा कोड",
            "رمز الصف",
            "Mã lớp"),
    CLASS_CODE_COPIED(
            "Class code copied to clipboard",
            "Kode kelas berhasil disalin ke clipboard",
            "クリップボードにクラスコードがコピーされました",
            "Código de clase copiado al portapapeles",
            "Klascode gekopieerd naar het klembord",
            "班级代码已复制到剪贴板",
            "클래스 코드가 클립 보드에 복사되었습니다",
            "कक्षा कोड क्लिपबोर्ड पर कॉपी किया गया",
            "تم نسخ رمز الصف إلى الحافظة",
            "Mã lớp đã được sao chép vào clipboard"),
    ASK_THE_TEACHER(
            "Ask the teacher",
            "Tanyakan kepada guru",
            "先生に聞いてみてください",
            "Pregúntale al profesor",
            "Vraag de leraar",
            "问老师",
            "선생님에게 물어보세요",
            "शिक्षक से पूछें",
            "اسأل المعلم",
            "Hỏi giáo viên"),
    FOR_THE_CLASS_CODE(
            "for the class code!",
            "untuk kode kelas!",
            "クラスコードのために！",
            "¡para el código de clase!",
            "voor de klascode!",
            "为班级代码！",
            "클래스 코드를위한!",
            "कक्षा कोड के लिए!",
            "بالنسبة لرمز الصف!",
            "cho mã lớp!"),
    REPLY_TO(
            "Reply to",
            "Balas kepada",
            "への返信",
            "Responder a",
            "Antwoord op",
            "回复",
            "에 대한 답장",
            "का जवाब दें",
            "الرد على",
            "Trả lời"),
    REPLY("Reply", "Balas", "リプライ", "Responder", "Antwoord", "回复", "답장", "जवाब दे", "الرد", "Trả lời"),
    VIEW_REPLIES(
            "View Replies",
            "Lihat Balasan",
            "返信を見る",
            "Ver respuestas",
            "Bekijk antwoorden",
            "查看回复",
            "답장보기",
            "उत्तर देखें",
            "عرض الردود",
            "Xem câu trả lời"),
    QUESTION_TYPE(
            "Question Type",
            "Jenis Pertanyaan",
            "質問のタイプ",
            "Tipo de pregunta",
            "Vraagtype",
            "问题类型",
            "질문 유형",
            "प्रश्न प्रकार",
            "نوع السؤال",
            "Loại câu hỏi"),
    ADD_TASK(
            "Add Task",
            "Tambahkan Tugas",
            "タスクを追加",
            "Agregar tarea",
            "Taak toevoegen",
            "添加任务",
            "작업 추가",
            "कार्य जोड़ें",
            "إضافة مهمة",
            "Thêm nhiệm vụ"),
    CREATE_TASK(
            "Create Task",
            "Buat Tugas",
            "タスクを作成",
            "Crear tarea",
            "Maak taak",
            "创建任务",
            "작업 만들기",
            "कार्य बनाएं",
            "إنشاء مهمة",
            "Tạo nhiệm vụ"),
    TASK_TYPE(
            "Task Type",
            "Jenis Tugas",
            "タスクの種類",
            "Tipo de tarea",
            "Taaktype",
            "任务类型",
            "작업 유형",
            "कार्य प्रकार",
            "نوع المهمة",
            "Loại nhiệm vụ"),
    TASK_LIST(
            "Task List",
            "Daftar Tugas",
            "タスクリスト",
            "Lista de tareas",
            "Takenlijst",
            "任务列表",
            "작업 목록",
            "कार्य सूची",
            "قائمة المهام",
            "Danh sách nhiệm vụ"),
    NO_STUDENT_YET(
            "No student yet",
            "Belum ada siswa",
            "生徒はまだいません",
            "Aún no hay estudiantes",
            "Nog geen studenten",
            "还没有学生",
            "아직 학생이 없습니다",
            "अभी तक कोई छात्र नहीं",
            "لا يوجد طالب حتى الآن",
            "Chưa có học sinh nào"),
    AVERAGE_STUDENT_SCORE(
            "Average Student Score",
            "Nilai Rata-rata Siswa",
            "平均生徒スコア",
            "Puntuación promedio del estudiante",
            "Gemiddelde studentenscore",
            "平均学生分数",
            "평균 학생 점수",
            "औसत छात्र स्कोर",
            "متوسط ​​درجة الطالب",
            "Điểm trung bình của học sinh"),
    TEACHER("Teacher", "Guru", "先生", "Profesor", "Leraar", "老师", "선생님", "शिक्षक", "معلم", "Giáo viên"),
    STUDENT("Student", "Siswa", "学生", "Estudiante", "Student", "学生", "학생", "छात्र", "طالب", "Học sinh"),
    NO_STUDENT_TO_TEACH(
            "No students yet to teach!",
            "Belum ada siswa untuk diajar!",
            "まだ教える生徒はいません！",
            "¡Aún no hay estudiantes para enseñar!",
            "Nog geen studenten om les te geven!",
            "还没有学生可以教！",
            "아직 가르칠 학생이 없습니다!",
            "अभी तक सिखाने के लिए कोई छात्र नहीं!",
            "لا يوجد طالب حتى الآن للتدريس!",
            "Chưa có học sinh nào để dạy!"),
    SOMETHING_UNEXPECTED_HAPPENED(
            "Something unexpected happened",
            "Ada sesuatu yang tidak terduga",
            "予期せぬことが起こりました",
            "Algo inesperado ocurrió",
            "Er gebeurde iets onverwachts",
            "发生了意外情况",
            "예기치 않은 일이 발생했습니다",
            "कुछ अप्रत्याशित हुआ",
            "حدث شيء غير متوقع",
            "Đã xảy ra điều gì đó bất ngờ"),
    FORUM("Forum", "Forum", "フォーラム", "Foro", "Forum", "论坛", "포럼", "फोरम", "منتدى", "Diễn đàn"),
    MEMBER("Member", "Anggota", "メンバー", "Miembro", "Lid", "成员", "회원", "सदस्य", "عضو", "Thành viên"),
    CREATE("Create", "Buat", "作成", "Crear", "Creëren", "创建", "만들기", "बनाएँ", "خلق", "Tạo"),
    CLASS_NAME(
            "Class Name",
            "Nama Kelas",
            "クラス名",
            "Nombre de la clase",
            "Klasnaam",
            "班级名称",
            "클래스 이름",
            "कक्षा का नाम",
            "اسم الصف",
            "Tên lớp"),
    CLASS_DESCRIPTION(
            "Class Description",
            "Deskripsi Kelas",
            "クラスの説明",
            "Descripción de la clase",
            "Klasbeschrijving",
            "班级描述",
            "클래스 설명",
            "कक्षा का विवरण",
            "وصف الصف",
            "Mô tả lớp"),
    CREATE_CLASS_SUCCESS(
            "Create Class Success!",
            "Berhasil Membuat Kelas!",
            "クラス作成に成功しました！",
            "¡Clase creada con éxito!",
            "Klas succesvol aangemaakt!",
            "创建班级成功！",
            "클래스 만들기 성공!",
            "कक्षा बनाने में सफलता!",
            "إنشاء فئة بنجاح!",
            "Tạo lớp thành công!"),
    FORUM_POSTED(
            "Forum Posted!",
            "Forum Diposting!",
            "フォーラムが投稿されました！",
            "¡Foro publicado!",
            "Forum gepost!",
            "论坛发布！",
            "포럼 게시 됨!",
            "फोरम पोस्ट किया गया!",
            "تم نشر المنتدى!",
            "Diễn đàn đã đăng!"),
    ANSWER_UPLOADED_SUCCESSFULLY(
            "Answer uploaded successfully!",
            "Jawaban berhasil diunggah!",
            "回答が正常にアップロードされました！",
            "¡Respuesta cargada con éxito!",
            "Antwoord succesvol geüpload!",
            "答案上传成功！",
            "답변이 성공적으로 업로드되었습니다!",
            "उत्तर सफलतापूर्वक अपलोड किया गया!",
            "تم تحميل الإجابة بنجاح!",
            "Trả lời được tải lên thành công!"),
    ALL_FIELDS_MUST_BE_FILLED(
            "All fields must be filled!",
            "Semua kolom harus diisi!",
            "すべてのフィールドを入力してください！",
            "Todos los campos deben estar llenos!",
            "Alle velden moeten worden ingevuld!",
            "所有字段都必须填写！",
            "모든 필드를 입력해야합니다!",
            "सभी फ़ील्ड भरे जाने चाहिए!",
            "يجب ملء جميع الحقول!",
            "Tất cả các trường phải được điền!"),
    NEW_PASSWORD_AND_CONFIRM_PASSWORD_MUST_BE_SAME(
            "New password and confirm password must be the same!",
            "Kata sandi baru dan konfirmasi kata sandi harus sama!",
            "新しいパスワードと確認パスワードは同じである必要があります！",
            "La nueva contraseña y la confirmación de la contraseña deben ser iguales!",
            "Nieuw wachtwoord en bevestigd wachtwoord moeten hetzelfde zijn!",
            "新密码和确认密码必须相同！",
            "새 비밀번호와 확인 비밀번호는 동일해야합니다!",
            "नया पासवर्ड और पासवर्ड की पुष्टि एक ही होनी चाहिए!",
            "يجب أن تكون كلمة المرور الجديدة وتأكيد كلمة المرور متطابقتين!",
            "Mật khẩu mới và xác nhận mật khẩu phải giống nhau!"),
    OLD_PASSWORD_IS_WRONG(
            "Old password is wrong!",
            "Kata sandi lama salah!",
            "古いパスワードが間違っています！",
            "La contraseña anterior es incorrecta!",
            "Oud wachtwoord is verkeerd!",
            "旧密码错误！",
            "이전 비밀번호가 잘못되었습니다!",
            "पुराना पासवर्ड गलत है!",
            "كلمة المرور القديمة خاطئة!",
            "Mật khẩu cũ là sai!"),
    PLEASE_FILL_ALL_THE_FIELDS(
            "Please fill all the fields!",
            "Harap isi semua kolom!",
            "すべてのフィールドを入力してください！",
            "Por favor complete todos los campos!",
            "Vul alle velden in aub!",
            "请填写所有字段！",
            "모든 필드를 입력하십시오!",
            "कृपया सभी फ़ील्ड भरें!",
            "يرجى ملء جميع الحقول!",
            "Vui lòng điền đầy đủ tất cả các trường!"),
    PASSWORD_MUST_BE_GREATER_THAN_8_CHARACTERS(
            "Password must be greater than 8 characters!",
            "Kata sandi harus lebih dari 8 karakter!",
            "パスワードは8文字以上である必要があります！",
            "La contraseña debe tener más de 8 caracteres!",
            "Wachtwoord moet meer dan 8 tekens bevatten!",
            "密码必须大于8个字符！",
            "비밀번호는 8 자보다 커야합니다!",
            "पासवर्ड 8 वर्णों से अधिक होना चाहिए!",
            "يجب أن تكون كلمة المرور أكثر من 8 أحرف!",
            "Mật khẩu phải dài hơn 8 ký tự!"),
    INVALID_EMAIL_FORMAT(
            "Invalid email format!",
            "Format email tidak valid!",
            "無効なメール形式！",
            "Formato de correo electrónico no válido!",
            "Ongeldig e-mailformaat!",
            "电子邮件格式无效！",
            "잘못된 이메일 형식!",
            "अमान्य ईमेल प्रारूप!",
            "تنسيق البريد الإلكتروني غير صالح!",
            "Định dạng email không hợp lệ!"),
    CLASS_CODE_MUST_BE_LESS_THAN_8_CHARACTERS(
            "Class code must be less than 8 characters!",
            "Kode kelas harus kurang dari 8 karakter!",
            "クラスコードは8文字未満である必要があります！",
            "El código de clase debe tener menos de 8 caracteres!",
            "Klascode moet minder dan 8 tekens bevatten!",
            "班级代码必须少于8个字符！",
            "클래스 코드는 8 자보다 적어야합니다!",
            "कक्षा कोड 8 वर्णों से कम होना चाहिए!",
            "يجب أن يكون رمز الصف أقل من 8 أحرف!",
            "Mã lớp phải ít hơn 8 ký tự!"),
    CLASS_CREATED_SUCCESSFULLY(
            "Class created successfully!",
            "Kelas berhasil dibuat!",
            "クラスが正常に作成されました！",
            "Clase creada exitosamente!",
            "Klas succesvol aangemaakt!",
            "班级创建成功！",
            "클래스가 성공적으로 만들어졌습니다!",
            "कक्षा सफलतापूर्वक बनाई गई!",
            "تم إنشاء الفئة بنجاح!",
            "Lớp học được tạo thành công!"),
    PLEASE_FILL_THE_GROUP_CODE(
            "Please fill the group code!",
            "Harap isi kode grup!",
            "グループコードを入力してください！",
            "Por favor complete el código de grupo!",
            "Vul de groepscode in aub!",
            "请填写组代码！",
            "그룹 코드를 입력하십시오!",
            "कृपया समूह कोड भरें!",
            "يرجى ملء رمز المجموعة!",
            "Vui lòng điền mã nhóm!"),
    GROUP_CODE_NOT_FOUND(
            "Group code not found!",
            "Kode grup tidak ditemukan!",
            "グループコードが見つかりません！",
            "Código de grupo no encontrado!",
            "Groepscode niet gevonden!",
            "找不到组代码！",
            "그룹 코드를 찾을 수 없습니다!",
            "समूह कोड नहीं मिला!",
            "لم يتم العثور على رمز المجموعة!",
            "Không tìm thấy mã nhóm!"),
    YOU_ARE_ALREADY_IN_THE_GROUP(
            "You are already in the group!",
            "Anda sudah bergabung dengan grup!",
            "すでにグループに参加しています！",
            "Ya estás en el grupo!",
            "Je zit al in de groep!",
            "您已经在该组中！",
            "이미 그룹에 있습니다!",
            "आप पहले से ही समूह में हैं!",
            "أنت بالفعل في المجموعة!",
            "Bạn đã ở trong nhóm!"),
    CLASS_JOINED_SUCCESSFULLY(
            "Class joined successfully!",
            "Bergabung dengan kelas berhasil!",
            "クラスに参加しました！",
            "Clase unida exitosamente!",
            "Klas succesvol toegevoegd!",
            "班级成功加入！",
            "클래스에 성공적으로 가입했습니다!",
            "कक्षा सफलतापूर्वक जुड़ी!",
            "تم الانضمام إلى الفئة بنجاح!",
            "Lớp học đã tham gia thành công!"),
    AGE_MUST_BE_GREATER_THAN_17(
            "Age must be greater than 17!",
            "Usia harus lebih dari 17 tahun!",
            "年齢は17歳以上である必要があります！",
            "La edad debe ser mayor de 17 años!",
            "Leeftijd moet ouder zijn dan 17 jaar!",
            "年龄必须大于17岁！",
            "나이는 17 세 이상이어야합니다!",
            "आयु 17 से अधिक होनी चाहिए!",
            "يجب أن يكون العمر أكبر من 17 عامًا!",
            "Tuổi phải lớn hơn 17 tuổi!"),
    EMAIL_OR_PASSWORD_IS_INCORRECT(
            "Email or password is incorrect!",
            "Email atau kata sandi salah!",
            "メールアドレスまたはパスワードが正しくありません！",
            "El correo electrónico o la contraseña son incorrectos!",
            "E-mail of wachtwoord is onjuist!",
            "电子邮件或密码不正确！",
            "이메일 또는 비밀번호가 잘못되었습니다!",
            "ईमेल या पासवर्ड गलत है!",
            "البريد الإلكتروني أو كلمة المرور غير صحيحة!",
            "Email hoặc mật khẩu không chính xác!"),
    LOGIN_SUCCESS(
            "Login Success!",
            "Login Berhasil!",
            "ログイン成功！",
            "Inicio de sesión exitoso!",
            "Inloggen gelukt!",
            "登录成功！",
            "로그인 성공!",
            "लॉगिन सफल!",
            "تسجيل الدخول بنجاح!",
            "Đăng nhập thành công!"),
    FILES_DOWNLOADED_SUCCESSFULLY(
            "Files downloaded successfully!",
            "File berhasil diunduh!",
            "ファイルが正常にダウンロードされました！",
            "Archivos descargados exitosamente!",
            "Bestanden succesvol gedownload!",
            "文件下载成功！",
            "파일이 성공적으로 다운로드되었습니다!",
            "फ़ाइलें सफलतापूर्वक डाउनलोड की गईं!",
            "تم تنزيل الملفات بنجاح!",
            "Tệp được tải xuống thành công!"),
    SCORE_CANNOT_BE_EMPTY(
            "Score cannot be empty!",
            "Nilai tidak boleh kosong!",
            "スコアは空にできません！",
            "La puntuación no puede estar vacía!",
            "Score kan niet leeg zijn!",
            "分数不能为空！",
            "점수는 비워 둘 수 없습니다!",
            "स्कोर खाली नहीं हो सकता!",
            "النتيجة لا يمكن أن تكون فارغة!",
            "Điểm không thể để trống!"),
    SCORE_MUST_BE_A_NUMBER(
            "Score must be a number!",
            "Nilai harus berupa angka!",
            "スコアは数値でなければなりません！",
            "La puntuación debe ser un número!",
            "Score moet een getal zijn!",
            "分数必须是一个数字！",
            "점수는 숫자 여야합니다!",
            "स्कोर एक नंबर होना चाहिए!",
            "يجب أن يكون النتيجة رقمًا!",
            "Điểm phải là một số!"),
    SCORE_MUST_BE_BETWEEN_0_AND_100(
            "Score must be between 0 and 100!",
            "Nilai harus antara 0 dan 100!",
            "スコアは0から100の間でなければなりません！",
            "La puntuación debe estar entre 0 y 100!",
            "Score moet tussen 0 en 100 liggen!",
            "分数必须介于0到100之间！",
            "점수는 0에서 100 사이 여야합니다!",
            "स्कोर 0 और 100 के बीच होना चाहिए!",
            "يجب أن يكون النتيجة بين 0 و 100!",
            "Điểm phải nằm trong khoảng từ 0 đến 100!"),
    CLASS_SUBJECT(
            "Class Subject",
            "Mata Pelajaran Kelas",
            "クラスの科目",
            "Materia de clase",
            "Vak van klas",
            "班级科目",
            "클래스 주제",
            "कक्षा विषय",
            "موضوع الصف",
            "Chủ đề lớp"),
    CREATE_NEW_TASK(
            "Create New Task",
            "Buat Tugas Baru",
            "新しいタスクを作成",
            "Crear nueva tarea",
            "Maak nieuwe taak",
            "创建新任务",
            "새 작업 만들기",
            "नया कार्य बनाएं",
            "إنشاء مهمة جديدة",
            "Tạo nhiệm vụ mới"),
    SCORED("Scored", "Nilai", "スコア", "Puntuado", "Scored", "得分", "점수", "स्कोर", "تم تسجيل النقاط", "Điểm"),
    ANSWER("Answer", "Jawaban", "回答", "Respuesta", "Antwoord", "答案", "대답", "उत्तर", "إجابة", "Trả lời"),
    CONSTRAINTS(
            "Constraints",
            "Kendala",
            "制約事項",
            "Restricciones",
            "Beperkingen",
            "约束",
            "제약 조건",
            "बाध्यताएं",
            "قيود",
            "Ràng buộc"),
    CONSTRAINT_RULE_ONE(
            "1. The answer must be a file.",
            "1. Jawaban harus berupa file.",
            "1. 回答は数字でなければなりません",
            "1. La respuesta debe ser un número",
            "1. Het antwoord moet een getal zijn",
            "1. 答案必须是一个数字",
            "1. 답변은 숫자 여야합니다",
            "1. उत्तर एक संख्या होनी चाहिए",
            "1. يجب أن يكون الجواب رقمًا",
            "1. Câu trả lời phải là một số"),
    CONSTRAINT_RULE_TWO(
            "2. File size must be less than 100kb.",
            "2. Jawaban tidak boleh lebih dari 100kb",
            "2. 答えは0から100の間の数字でなければなりません",
            "2. La respuesta debe ser un número entre 0 y 100",
            "2. Het antwoord moet een getal zijn tussen 0 en 100",
            "2. 答案必须是0到100之间的数字",
            "2. 답변은 0에서 100 사이의 숫자 여야합니다",
            "2. उत्तर 0 और 100 के बीच एक संख्या होनी चाहिए",
            "2. يجب أن يكون الجواب رقمًا بين 0 و 100",
            "2. Câu trả lời phải là một số từ 0 đến 100"),
    GET_ANSWER(
            "Get Answer",
            "Dapatkan Jawaban",
            "答えを取得",
            "Obtener respuesta",
            "Krijg antwoord",
            "得到答案",
            "답변 받기",
            "उत्तर प्राप्त करें",
            "الحصول على الإجابة",
            "Nhận câu trả lời"),
    DOWNLOAD("Download", "Unduh", "ダウンロード", "Descargar", "Downloaden", "下载", "다운로드", "डाउनलोड", "تحميل", "Tải xuống"),
    DO_TEST(
            "Do Test",
            "Kerjakan Tes",
            "テストを受ける",
            "Hacer prueba",
            "Doe de test",
            "做测试",
            "테스트하기",
            "परीक्षा दें",
            "اختبار",
            "Làm bài kiểm tra"),
    DONE("Done", "Selesai", "完了", "Hecho", "Klaar", "完成", "완료", "किया हुआ", "فعله", "Làm xong"),
    NOT_DONE(
            "Not Done",
            "Belum Selesai",
            "未完了",
            "No hecho",
            "Niet gedaan",
            "未完成",
            "미완료",
            "नहीं किया",
            "لم يتم",
            "Chưa làm"),
    NOT_ATTEMPTED(
            "Not Attempted",
            "Belum Dicoba",
            "未試行",
            "No intentado",
            "Niet geprobeerd",
            "未尝试",
            "시도하지 않음",
            "प्रयास नहीं किया",
            "لم يتم المحاولة",
            "Không thử"),
    SUBMITTED(
            "Submitted",
            "Dikumpulkan",
            "提出",
            "Enviado",
            "Ingezonden",
            "提交",
            "제출 됨",
            "प्रस्तुत",
            "تم الإرسال",
            "Đã gửi"),
    FALSE("False", "Salah", "偽", "Falso", "False", "假", "거짓", "झूठा", "خطأ", "Sai"),
    SCORE("Score", "Nilai", "スコア", "Puntuación", "Score", "得分", "점수", "स्कोर", "نقاط", "Điểm"),
    ENTER_ANSWER_HERE(
            "Enter Answer Here",
            "Masukkan Jawaban di Sini",
            "ここに回答を入力してください",
            "Ingrese la respuesta aquí",
            "Voer hier het antwoord in",
            "输入答案",
            "답변을 여기에 입력하십시오",
            "यहाँ उत्तर दें",
            "أدخل الإجابة هنا",
            "Nhập câu trả lời vào đây"),
    ENTER_QUESTION_HERE(
            "Enter Question Here",
            "Masukkan Pertanyaan di Sini",
            "ここに質問を入力してください",
            "Ingrese la pregunta aquí",
            "Voer hier de vraag in",
            "输入问题",
            "여기에 질문을 입력하십시오",
            "यहाँ प्रश्न दें",
            "أدخل السؤال هنا",
            "Nhập câu hỏi vào đây"),
    ENTER_CHOICE_HERE(
            "Enter Choice Here",
            "Masukkan Pilihan di Sini",
            "ここに選択肢を入力してください",
            "Ingrese la opción aquí",
            "Voer hier de keuze in",
            "输入选择",
            "여기에 선택을 입력하십시오",
            "यहाँ विकल्प दें",
            "أدخل الخيار هنا",
            "Nhập lựa chọn vào đây"),
    TASK_TITLE(
            "Task Title",
            "Judul Tugas",
            "タスクタイトル",
            "Título de la tarea",
            "Taak titel",
            "任务标题",
            "작업 제목",
            "कार्य शीर्षक",
            "عنوان المهمة",
            "Tiêu đề nhiệm vụ"),
    TASK_DESCRIPTION(
            "Task Description",
            "Deskripsi Tugas",
            "タスクの説明",
            "Descripción de la tarea",
            "Taakomschrijving",
            "任务描述",
            "작업 설명",
            "कार्य विवरण",
            "وصف المهمة",
            "Mô tả nhiệm vụ"),
    REGISTER("Register", "Daftar", "登録", "Registrarse", "Registreren", "寄存器", "레지스터", "रजिस्टर", "تسجيل", "Đăng ký"),
    REGISTER_SUCCESS(
            "Register Success",
            "Pendaftaran Berhasil",
            "登録成功",
            "Registro exitoso",
            "Registratie succesvol",
            "注册成功",
            "등록 성공",
            "रजिस्टर सफल",
            "تسجيل ناجح",
            "Đăng ký thành công"),
    ALREADY_HAVE_AN_ACCOUNT(
            "Already have an account? Login here!",
            "Sudah memiliki akun? Masuk di sini!",
            "すでにアカウントをお持ちですか？こちらでログイン！",
            "¿Ya tienes una cuenta? Inicia sesión aquí!",
            "Heb je al een account? Log hier in!",
            "已经有一个帐户了吗？在这里登录！",
            "이미 계정이 있습니까? 여기에서 로그인!",
            "पहले से ही खाता है? यहाँ लॉगिन करें!",
            "هل لديك حساب بالفعل؟ تسجيل الدخول هنا!",
            "Đã có tài khoản? Đăng nhập ở đây!"),
    BE_THE_CHANGE(
            "Be the change, sign in to make it happen!",
            "Jadilah perubahan, masuk untuk mewujudkannya!",
            "変化を起こしましょう、サインインして実現しましょう！",
            "Sé el cambio, inicia sesión para que suceda!",
            "Wees de verandering, meld je aan om het te laten gebeuren!",
            "成为改变，登录以实现它！",
            "변화가되어보세요. 로그인하여 일어나게하십시오!",
            "परिवर्तन बनें, इसे होने दें के लिए साइन इन करें!",
            "كن التغيير ، سجل الدخول لجعله يحدث!",
            "Hãy làm thay đổi, đăng nhập để thực hiện điều đó!"),
    NAME("Name", "Nama", "名前", "Nombre", "Naam", "名称", "이름", "नाम", "اسم", "Tên"),
    EMAIL(
            "Email",
            "Email",
            "電子メール",
            "Correo electrónico",
            "E-mail",
            "电子邮件",
            "이메일",
            "ईमेल",
            "البريد الإلكتروني",
            "E-mail"),
    PASSWORD(
            "Password",
            "Kata Sandi",
            "パスワード",
            "Contraseña",
            "Wachtwoord",
            "密码",
            "암호",
            "पासवर्ड",
            "كلمه السر",
            "Mật khẩu"),
    CONFIRM_PASSWORD(
            "Confirm Password",
            "Konfirmasi Kata Sandi",
            "パスワードを確認",
            "Confirmar contraseña",
            "Bevestig wachtwoord",
            "确认密码",
            "비밀번호 확인",
            "पासवर्ड की पुष्टि कीजिये",
            "تأكيد كلمة المرور",
            "Xác nhận mật khẩu"),
    DATE_OF_BIRTH(
            "Date of Birth",
            "Tanggal Lahir",
            "生年月日",
            "Fecha de nacimiento",
            "Geboortedatum",
            "出生日期",
            "생년월일",
            "जन्म की तारीख",
            "تاريخ الولادة",
            "Ngày sinh"),
    ANSWER_KEY(
            "Answer Key",
            "Kunci Jawaban",
            "答えの鍵",
            "Clave de respuesta",
            "Antwoordsleutel",
            "答案",
            "답변 키",
            "उत्तर कुंजी",
            "مفتاح الإجابة",
            "Chìa khóa trả lời"),
    UPLOAD_FILE(
            "Upload File",
            "Unggah File",
            "ファイルをアップロード",
            "Subir archivo",
            "Upload bestand",
            "上传文件",
            "파일 업로드",
            "फ़ाइल अपलोड करें",
            "تحميل الملف",
            "Tải tệp lên"),
    DROP_YOUR_FILE_HERE(
            "Drop your file here",
            "Letakkan file Anda di sini",
            "ファイルをこちらにドロップ",
            "Suelta tu archivo aquí",
            "Zet hier je bestand neer",
            "将文件拖到此处",
            "여기에 파일을 드롭하십시오",
            "अपनी फ़ाइल यहाँ छोड़ें",
            "أسقط ملفك هنا",
            "Thả tệp của bạn vào đây"),
    UPLOAD("Upload", "Unggah", "アップロード", "Subir", "Uploaden", "上传", "업로드", "अपलोड", "تحميل", "Tải lên"),
    FILES("Files", "File", "ファイル", "Archivos", "Bestanden", "文件", "파일", "फ़ाइलें", "ملفات", "Tập tin"),
    FILE_EXCEEDS_LIMIT(
            "File already exists or exceeds 100 kilobytes",
            "File sudah ada atau melebihi 100 kilobyte",
            "ファイルはすでに存在するか、100キロバイトを超えています",
            "El archivo ya existe o excede los 100 kilobytes",
            "Bestand bestaat al of overschrijdt 100 kilobytes",
            "文件已存在或超过100千字节",
            "파일이 이미 있거나 100 킬로바이트를 초과합니다",
            "फ़ाइल पहले से मौजूद है या 100 किलोबाइट से अधिक है",
            "الملف موجود بالفعل أو يتجاوز 100 كيلوبايت",
            "Tệp đã tồn tại hoặc vượt quá 100 kilobyte"),
    CHOOSE_FILE(
            "Choose File",
            "Pilih File",
            "ファイルを選択",
            "Elegir archivo",
            "Kies bestand",
            "选择文件",
            "파일 선택",
            "फ़ाइल चुनें",
            "اختر ملف",
            "Chọn tệp"),
    NO_FILES_SELECTED(
            "No files selected",
            "Tidak ada file yang dipilih",
            "ファイルが選択されていません",
            "No se ha seleccionado ningún archivo",
            "Geen bestanden geselecteerd",
            "未选择文件",
            "선택된 파일 없음",
            "कोई फ़ाइल चयनित नहीं",
            "لم يتم تحديد أي ملفات",
            "Không có tệp nào được chọn"),
    POSTED_BY(
            "Posted by",
            "Diposting oleh",
            "投稿者",
            "Publicado por",
            "Geplaatst door",
            "发布者",
            "게시자",
            "द्वारा पोस्ट किया गया",
            "نشر من قبل",
            "Được đăng bởi"),
    DEADLINE(
            "Deadline",
            "Batas Waktu",
            "締め切り",
            "Fecha límite",
            "Deadline",
            "截止日期",
            "마감",
            "समय सीमा",
            "الموعد النهائي",
            "Hạn chót"),
    ADD_COMMENT(
            "Add Comment",
            "Tambahkan Komentar",
            "コメントを追加",
            "Agregar comentario",
            "Voeg een opmerking toe",
            "添加评论",
            "댓글 추가",
            "टिप्पणी जोड़ें",
            "إضافة تعليق",
            "Thêm bình luận"),
    WRITE_COMMENT_HERE(
            "Write comment here",
            "Tulis komentar di sini",
            "ここにコメントを書いてください",
            "Escribe tu comentario aquí",
            "Schrijf hier je opmerking",
            "在此处写下您的评论",
            "여기에 댓글을 작성하십시오",
            "यहाँ टिप्पणी लिखें",
            "اكتب تعليقك هنا",
            "Viết bình luận của bạn ở đây"),
    SUBMIT("Submit", "Kirim", "提出", "Enviar", "Verstuur", "提交", "제출", "जमा करें", "إرسال", "Gửi đi"),
    MARK_AS_DONE(
            "Mark as Done",
            "Tandai Selesai",
            "完了としてマーク",
            "Marcar como hecho",
            "Markeer als voltooid",
            "标记为完成",
            "완료로 표시",
            "समाप्त के रूप में चिह्नित करें",
            "علامة كما تم",
            "Đánh dấu là đã xong"),
    SUBMIT_TASK(
            "Submit Task",
            "Kumpulkan Tugas",
            "タスクを提出",
            "Enviar tarea",
            "Taak indienen",
            "提交任务",
            "작업 제출",
            "कार्य जमा करें",
            "إرسال المهمة",
            "Gửi nhiệm vụ"),
    NOT_SUBMITTED(
            "Not Submitted",
            "Belum Dikumpulkan",
            "未提出",
            "No enviado",
            "Niet ingediend",
            "未提交",
            "제출되지 않음",
            "जमा नहीं किया गया",
            "لم يتم الإرسال",
            "Không được gửi"),
    CANDLE_SHINE_WHEN_BURNED(
            "Candle shine when burned",
            "Lilin bersinar ketika terbakar",
            "キャンドルは燃えると輝く",
            "La vela brilla cuando se quema",
            "Kaars schijnt als hij brandt",
            "蜡烛燃烧时发光",
            "촛불이 타면 빛납니다",
            "मोमबत्ती जलते ही चमकती है",
            "الشمعة تلمع عندما تحترق",
            "Nến sáng khi đốt"),
    HOP_IN_AND_LETS_INITIATE_GREATNESS(
            "Hop in and let's initiate greatness",
            "Bergabung dan mari kita mulai kehebatan",
            "ホップインして偉大さを開始しましょう",
            "Salta y vamos a iniciar la grandeza",
            "Stap in en laten we grootsheid initiëren",
            "跳进来，让我们开始伟大",
            "들어와서 위대함을 시작합시다",
            "उछलो और महानता की शुरुआत करें",
            "اقفز ولنبدأ العظمة",
            "Nhảy vào và hãy khởi đầu vĩ đại"),
    DONT_HAVE_AN_ACCOUNT(
            "Don't have an account? Register here!",
            "Belum memiliki akun? Daftar di sini!",
            "アカウントをお持ちでない場合は、こちらで登録してください！",
            "¿No tienes una cuenta? ¡Regístrate aquí!",
            "Heb je geen account? Registreer hier!",
            "没有帐户？在这里注册！",
            "계정이 없으십니까? 여기에서 등록하십시오!",
            "खाता नहीं है? यहाँ रजिस्टर करें!",
            "ليس لديك حساب؟ سجل هنا!",
            "Bạn không có tài khoản? Đăng ký ở đây!"),
    START_JOURNEY(
            "Start Journey",
            "Mulai Perjalanan",
            "旅を始めよう",
            "Comienza el viaje",
            "Begin de reis",
            "开始旅程",
            "여정 시작",
            "यात्रा शुरू करें",
            "بدء الرحلة",
            "Bắt đầu hành trình"),
    REMEMBER_ME(
            "Remember Me",
            "Ingat Saya",
            "私を覚えてますか",
            "Recuérdame",
            "Onthoud mij",
            "记住我",
            "나를 기억해",
            "मुझे याद रखना",
            "تذكرنى",
            "Nhớ tôi"),
    WELCOME_BACK(
            "Welcome Back",
            "Selamat Datang Kembali",
            "おかえりなさい",
            "Bienvenido de nuevo",
            "Welkom terug",
            "欢迎回来",
            "다시 오신 것을 환영합니다",
            "वापसी पर स्वागत है",
            "مرحبا بعودتك",
            "Chào mừng trở lại"),
    CHOOSE_A_STUDENT_TO_SEE_THE_ANSWER(
            "Choose a student to see the answer",
            "Pilih siswa untuk melihat jawabannya",
            "答えを見るために生徒を選択してください",
            "Elija un estudiante para ver la respuesta",
            "Kies een student om het antwoord te zien",
            "选择一个学生来查看答案",
            "답변을 보려면 학생을 선택하십시오",
            "उत्तर देखने के लिए एक छात्र का चयन करें",
            "اختر طالبًا لرؤية الإجابة",
            "Chọn một học sinh để xem câu trả lời"),
    STUDENT_ANSWER(
            "Student Answer",
            "Jawaban Siswa",
            "学生の答え",
            "Respuesta del estudiante",
            "Student antwoord",
            "学生答案",
            "학생 답변",
            "छात्र उत्तर",
            "إجابة الطالب",
            "Câu trả lời của học sinh"),
    NO_FILE_UPLOADED(
            "No file uploaded",
            "Tidak ada file yang diunggah",
            "ファイルがアップロードされていません",
            "Ningún archivo cargado",
            "Geen bestand geüpload",
            "没有上传文件",
            "파일이 업로드되지 않았습니다",
            "कोई फ़ाइल अपलोड नहीं की गई",
            "لم يتم تحميل أي ملف",
            "Không có tệp nào được tải lên"),
    HELLO("Hello", "Halo", "こんにちは", "Hola", "Hallo", "你好", "안녕", "नमस्ते", "مرحبا", "Xin chào"),
    ;

    private final Map<Language, String> text = new HashMap<>();

    Text(String text) {
        for (Language language : Language.values()) {
            this.text.put(language, text);
        }
    }

    public String getText(Language language) {
        return text.get(language);
    }

    Text(String english, String indonesian) {
        for (Language language : Language.values()) {
            if (language.equals(Language.ENGLISH)) {
                this.text.put(language, english);
            }
            if (language.equals(Language.INDONESIAN)) {
                this.text.put(language, indonesian);
                continue;
            }
        }
    }

    Text(
            String english,
            String indonesian,
            String japanese,
            String spanish,
            String dutch,
            String chinese,
            String korean,
            String indian,
            String arabic,
            String vietnamese) {
        for (Language language : Language.values()) {
            if (language.equals(Language.ENGLISH)) {
                this.text.put(language, english);
            }
            if (language.equals(Language.INDONESIAN)) {
                this.text.put(language, indonesian);
                continue;
            }
            if (language.equals(Language.JAPANESE)) {
                this.text.put(language, japanese);
                continue;
            }
            if (language.equals(Language.SPANISH)) {
                this.text.put(language, spanish);
                continue;
            }
            if (language.equals(Language.DUTCH)) {
                this.text.put(language, dutch);
                continue;
            }
            if (language.equals(Language.CHINESE)) {
                this.text.put(language, chinese);
                continue;
            }
            if (language.equals(Language.KOREAN)) {
                this.text.put(language, korean);
                continue;
            }
            if (language.equals(Language.INDIAN)) {
                this.text.put(language, indian);
                continue;
            }
            if (language.equals(Language.ARABIC)) {
                this.text.put(language, arabic);
                continue;
            }
            if (language.equals(Language.VIETNAMESE)) {
                this.text.put(language, vietnamese);
            }
        }
    }
}
